import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from "@/app/NavBar";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Fortune-3D',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  console.log(children)
  return (
    <html lang="en">
      <body className={inter.className}>
      <NavBar />
      {children}
      </body>
    </html>
  )
}
